# core/execution/analysis/authorization_baseline_store.py

from copy import deepcopy


class AuthorizationBaselineStore:
    """
    In-memory store for authorization baseline evidence.

    The store is intentionally simple and deterministic. It stores
    authorized baseline evidence by stable baseline keys generated by
    AuthorizationBaselineKeyBuilder.

    It does not execute HTTP requests and does not decide whether a
    resource is vulnerable. It only stores and retrieves baseline
    evidence safely.
    """

    def __init__(
        self,
        initial_baselines: dict[str, dict] | None = None,
    ):
        self._baselines: dict[str, dict] = {}

        for key, evidence in (
            initial_baselines or {}
        ).items():
            self.save(
                key=key,
                evidence=evidence,
            )

    def save(
        self,
        key: str,
        evidence: dict,
    ) -> None:
        normalized_key = self._normalize_key(
            key
        )

        if evidence is None:
            raise ValueError(
                "Baseline evidence is required."
            )

        self._baselines[normalized_key] = deepcopy(
            evidence
        )

    def get(
        self,
        key: str,
    ) -> dict | None:
        normalized_key = self._normalize_key(
            key
        )

        evidence = self._baselines.get(
            normalized_key
        )

        if evidence is None:
            return None

        return deepcopy(
            evidence
        )

    def has(
        self,
        key: str,
    ) -> bool:
        normalized_key = self._normalize_key(
            key
        )

        return normalized_key in self._baselines

    def delete(
        self,
        key: str,
    ) -> bool:
        normalized_key = self._normalize_key(
            key
        )

        return (
            self._baselines.pop(
                normalized_key,
                None,
            )
            is not None
        )

    def clear(
        self,
    ) -> None:
        self._baselines.clear()

    def keys(
        self,
    ) -> tuple[str, ...]:
        return tuple(
            sorted(
                self._baselines.keys()
            )
        )

    def __len__(
        self,
    ) -> int:
        return len(
            self._baselines
        )

    def _normalize_key(
        self,
        key: str,
    ) -> str:
        if not isinstance(
            key,
            str,
        ):
            raise ValueError(
                "Baseline key must be a string."
            )

        normalized = key.strip()

        if not normalized:
            raise ValueError(
                "Baseline key is required."
            )

        return normalized